// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: api/v1/sync_backend.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncBackendSetupConnectionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId string `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SyncBackendSetupConnectionRequest) Reset() {
	*x = SyncBackendSetupConnectionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendSetupConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendSetupConnectionRequest) ProtoMessage() {}

func (x *SyncBackendSetupConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendSetupConnectionRequest.ProtoReflect.Descriptor instead.
func (*SyncBackendSetupConnectionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{0}
}

func (x *SyncBackendSetupConnectionRequest) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *SyncBackendSetupConnectionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SyncBackendSetupConnectionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncBackendSetupConnectionResponse) Reset() {
	*x = SyncBackendSetupConnectionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendSetupConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendSetupConnectionResponse) ProtoMessage() {}

func (x *SyncBackendSetupConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendSetupConnectionResponse.ProtoReflect.Descriptor instead.
func (*SyncBackendSetupConnectionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{1}
}

type SyncBackendIncomingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*SyncBackendIncomingMessage_Connect
	//	*SyncBackendIncomingMessage_Update
	Msg isSyncBackendIncomingMessage_Msg `protobuf_oneof:"msg"`
}

func (x *SyncBackendIncomingMessage) Reset() {
	*x = SyncBackendIncomingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendIncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendIncomingMessage) ProtoMessage() {}

func (x *SyncBackendIncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendIncomingMessage.ProtoReflect.Descriptor instead.
func (*SyncBackendIncomingMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{2}
}

func (m *SyncBackendIncomingMessage) GetMsg() isSyncBackendIncomingMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *SyncBackendIncomingMessage) GetConnect() *SyncBackendConnectRequest {
	if x, ok := x.GetMsg().(*SyncBackendIncomingMessage_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *SyncBackendIncomingMessage) GetUpdate() *SyncBackendIncomingUpdate {
	if x, ok := x.GetMsg().(*SyncBackendIncomingMessage_Update); ok {
		return x.Update
	}
	return nil
}

type isSyncBackendIncomingMessage_Msg interface {
	isSyncBackendIncomingMessage_Msg()
}

type SyncBackendIncomingMessage_Connect struct {
	Connect *SyncBackendConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type SyncBackendIncomingMessage_Update struct {
	Update *SyncBackendIncomingUpdate `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

func (*SyncBackendIncomingMessage_Connect) isSyncBackendIncomingMessage_Msg() {}

func (*SyncBackendIncomingMessage_Update) isSyncBackendIncomingMessage_Msg() {}

type SyncBackendConnectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MapId    string `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *SyncBackendConnectRequest) Reset() {
	*x = SyncBackendConnectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendConnectRequest) ProtoMessage() {}

func (x *SyncBackendConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendConnectRequest.ProtoReflect.Descriptor instead.
func (*SyncBackendConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{3}
}

func (x *SyncBackendConnectRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SyncBackendConnectRequest) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *SyncBackendConnectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SyncBackendIncomingUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq    int32  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Aware  []byte `protobuf:"bytes,3,opt,name=aware,proto3" json:"aware,omitempty"`   // json
	Change []byte `protobuf:"bytes,4,opt,name=change,proto3" json:"change,omitempty"` // json
}

func (x *SyncBackendIncomingUpdate) Reset() {
	*x = SyncBackendIncomingUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendIncomingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendIncomingUpdate) ProtoMessage() {}

func (x *SyncBackendIncomingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendIncomingUpdate.ProtoReflect.Descriptor instead.
func (*SyncBackendIncomingUpdate) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{4}
}

func (x *SyncBackendIncomingUpdate) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SyncBackendIncomingUpdate) GetAware() []byte {
	if x != nil {
		return x.Aware
	}
	return nil
}

func (x *SyncBackendIncomingUpdate) GetChange() []byte {
	if x != nil {
		return x.Change
	}
	return nil
}

type SyncBackendOutgoingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ack                 int32  `protobuf:"varint,1,opt,name=ack,proto3" json:"ack,omitempty"`
	InitialLoadComplete bool   `protobuf:"varint,4,opt,name=initialLoadComplete,proto3" json:"initialLoadComplete,omitempty"` // set to true to indicate the initial load is complete
	Aware               []byte `protobuf:"bytes,2,opt,name=aware,proto3" json:"aware,omitempty"`                              // json
	Change              []byte `protobuf:"bytes,3,opt,name=change,proto3" json:"change,omitempty"`                            // json
}

func (x *SyncBackendOutgoingMessage) Reset() {
	*x = SyncBackendOutgoingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendOutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendOutgoingMessage) ProtoMessage() {}

func (x *SyncBackendOutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendOutgoingMessage.ProtoReflect.Descriptor instead.
func (*SyncBackendOutgoingMessage) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{5}
}

func (x *SyncBackendOutgoingMessage) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *SyncBackendOutgoingMessage) GetInitialLoadComplete() bool {
	if x != nil {
		return x.InitialLoadComplete
	}
	return false
}

func (x *SyncBackendOutgoingMessage) GetAware() []byte {
	if x != nil {
		return x.Aware
	}
	return nil
}

func (x *SyncBackendOutgoingMessage) GetChange() []byte {
	if x != nil {
		return x.Change
	}
	return nil
}

type SyncBackendExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connect  *SyncBackendConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3" json:"connect,omitempty"`
	Format   string                     `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Name     string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Filename string                     `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *SyncBackendExportRequest) Reset() {
	*x = SyncBackendExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendExportRequest) ProtoMessage() {}

func (x *SyncBackendExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendExportRequest.ProtoReflect.Descriptor instead.
func (*SyncBackendExportRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{6}
}

func (x *SyncBackendExportRequest) GetConnect() *SyncBackendConnectRequest {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *SyncBackendExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SyncBackendExportRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SyncBackendExportRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type SyncBackendExportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *SyncBackendExportResponse) Reset() {
	*x = SyncBackendExportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendExportResponse) ProtoMessage() {}

func (x *SyncBackendExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendExportResponse.ProtoReflect.Descriptor instead.
func (*SyncBackendExportResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{7}
}

func (x *SyncBackendExportResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type SyncBackendImportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Connect              *SyncBackendConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3" json:"connect,omitempty"`
	Url                  string                     `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Format               string                     `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	ImportId             string                     `protobuf:"bytes,4,opt,name=import_id,json=importId,proto3" json:"import_id,omitempty"`
	ImportedFromFilename string                     `protobuf:"bytes,5,opt,name=imported_from_filename,json=importedFromFilename,proto3" json:"imported_from_filename,omitempty"`
}

func (x *SyncBackendImportRequest) Reset() {
	*x = SyncBackendImportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendImportRequest) ProtoMessage() {}

func (x *SyncBackendImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendImportRequest.ProtoReflect.Descriptor instead.
func (*SyncBackendImportRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{8}
}

func (x *SyncBackendImportRequest) GetConnect() *SyncBackendConnectRequest {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *SyncBackendImportRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SyncBackendImportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SyncBackendImportRequest) GetImportId() string {
	if x != nil {
		return x.ImportId
	}
	return ""
}

func (x *SyncBackendImportRequest) GetImportedFromFilename() string {
	if x != nil {
		return x.ImportedFromFilename
	}
	return ""
}

type SyncBackendImportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SyncBackendImportResponse) Reset() {
	*x = SyncBackendImportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_sync_backend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncBackendImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBackendImportResponse) ProtoMessage() {}

func (x *SyncBackendImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_sync_backend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBackendImportResponse.ProtoReflect.Descriptor instead.
func (*SyncBackendImportResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_sync_backend_proto_rawDescGZIP(), []int{9}
}

var File_api_v1_sync_backend_proto protoreflect.FileDescriptor

var file_api_v1_sync_backend_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x21, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x70,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x24, 0x0a, 0x22, 0x53, 0x79, 0x6e, 0x63,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x91,
	0x01, 0x0a, 0x1a, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6e,
	0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x34, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x05, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x65, 0x0a, 0x19, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x19, 0x53, 0x79, 0x6e,
	0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x77, 0x61, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x77, 0x61, 0x72, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x8e, 0x01, 0x0a, 0x1a, 0x53, 0x79, 0x6e, 0x63, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x30, 0x0a, 0x13, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x4c, 0x6f, 0x61, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x4c, 0x6f, 0x61,
	0x64, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x77, 0x61,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x77, 0x61, 0x72, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x98, 0x01, 0x0a, 0x18, 0x53, 0x79, 0x6e, 0x63,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x19, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0xcd, 0x01, 0x0a, 0x18, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x65, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x1b, 0x0a, 0x19, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xee,
	0x02, 0x0a, 0x0b, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x5a,
	0x0a, 0x0f, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x1b, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x4f, 0x75, 0x74, 0x67, 0x6f, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x3f, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x19, 0x2e,
	0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x19,
	0x2e, 0x53, 0x79, 0x6e, 0x63, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61,
	0x6e, 0x69, 0x65, 0x6c, 0x7a, 0x66, 0x72, 0x61, 0x6e, 0x6b, 0x6c, 0x69, 0x6e, 0x2f, 0x70, 0x6c,
	0x61, 0x6e, 0x74, 0x6f, 0x70, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_sync_backend_proto_rawDescOnce sync.Once
	file_api_v1_sync_backend_proto_rawDescData = file_api_v1_sync_backend_proto_rawDesc
)

func file_api_v1_sync_backend_proto_rawDescGZIP() []byte {
	file_api_v1_sync_backend_proto_rawDescOnce.Do(func() {
		file_api_v1_sync_backend_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_sync_backend_proto_rawDescData)
	})
	return file_api_v1_sync_backend_proto_rawDescData
}

var file_api_v1_sync_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_sync_backend_proto_goTypes = []interface{}{
	(*SyncBackendSetupConnectionRequest)(nil),  // 0: SyncBackendSetupConnectionRequest
	(*SyncBackendSetupConnectionResponse)(nil), // 1: SyncBackendSetupConnectionResponse
	(*SyncBackendIncomingMessage)(nil),         // 2: SyncBackendIncomingMessage
	(*SyncBackendConnectRequest)(nil),          // 3: SyncBackendConnectRequest
	(*SyncBackendIncomingUpdate)(nil),          // 4: SyncBackendIncomingUpdate
	(*SyncBackendOutgoingMessage)(nil),         // 5: SyncBackendOutgoingMessage
	(*SyncBackendExportRequest)(nil),           // 6: SyncBackendExportRequest
	(*SyncBackendExportResponse)(nil),          // 7: SyncBackendExportResponse
	(*SyncBackendImportRequest)(nil),           // 8: SyncBackendImportRequest
	(*SyncBackendImportResponse)(nil),          // 9: SyncBackendImportResponse
	(*emptypb.Empty)(nil),                      // 10: google.protobuf.Empty
	(*structpb.Struct)(nil),                    // 11: google.protobuf.Struct
}
var file_api_v1_sync_backend_proto_depIdxs = []int32{
	3,  // 0: SyncBackendIncomingMessage.connect:type_name -> SyncBackendConnectRequest
	4,  // 1: SyncBackendIncomingMessage.update:type_name -> SyncBackendIncomingUpdate
	3,  // 2: SyncBackendExportRequest.connect:type_name -> SyncBackendConnectRequest
	3,  // 3: SyncBackendImportRequest.connect:type_name -> SyncBackendConnectRequest
	0,  // 4: SyncBackend.SetupConnection:input_type -> SyncBackendSetupConnectionRequest
	2,  // 5: SyncBackend.Connect:input_type -> SyncBackendIncomingMessage
	6,  // 6: SyncBackend.Export:input_type -> SyncBackendExportRequest
	8,  // 7: SyncBackend.Import:input_type -> SyncBackendImportRequest
	10, // 8: SyncBackend.Stats:input_type -> google.protobuf.Empty
	1,  // 9: SyncBackend.SetupConnection:output_type -> SyncBackendSetupConnectionResponse
	5,  // 10: SyncBackend.Connect:output_type -> SyncBackendOutgoingMessage
	7,  // 11: SyncBackend.Export:output_type -> SyncBackendExportResponse
	9,  // 12: SyncBackend.Import:output_type -> SyncBackendImportResponse
	11, // 13: SyncBackend.Stats:output_type -> google.protobuf.Struct
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_v1_sync_backend_proto_init() }
func file_api_v1_sync_backend_proto_init() {
	if File_api_v1_sync_backend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_sync_backend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendSetupConnectionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendSetupConnectionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendIncomingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendConnectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendIncomingUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendOutgoingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendExportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendImportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_sync_backend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncBackendImportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_sync_backend_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SyncBackendIncomingMessage_Connect)(nil),
		(*SyncBackendIncomingMessage_Update)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_sync_backend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_sync_backend_proto_goTypes,
		DependencyIndexes: file_api_v1_sync_backend_proto_depIdxs,
		MessageInfos:      file_api_v1_sync_backend_proto_msgTypes,
	}.Build()
	File_api_v1_sync_backend_proto = out.File
	file_api_v1_sync_backend_proto_rawDesc = nil
	file_api_v1_sync_backend_proto_goTypes = nil
	file_api_v1_sync_backend_proto_depIdxs = nil
}
