/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

import * as geojson from 'geojson';

export interface paths {
  '/auth/authenticate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authenticate as a user (see /auth/authenticate-browser if you are the frontend) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthenticateReq'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthenticateOK'];
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/authenticate-browser': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate and store the token in the requesting browser's cookie jar
     * @description This sets a cookie authenticating you as the given user. The cookie will only work on plantopo.com
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthenticateReq'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            'Set-Cookie'?: components['schemas']['SetSessionCookieHeader'];
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthenticateBrowserOK'];
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/check': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Check if you are authenticated */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              userID: components['schemas']['UserID'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the authenticated user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              user: components['schemas']['User'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new account */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthRegisterRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthenticateOK'];
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register-browser': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new account and store the token in the requesting browser's cookie jar */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthRegisterRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            'Set-Cookie'?: components['schemas']['SetSessionCookieHeader'];
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthenticateBrowserOK'];
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke a token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AuthRevokeReq'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': Record<string, never>;
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/revoke-browser': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke the token stored in the requesting browser's cookie jar
     * @description Revokes the cookie set by /auth/authenticate-browser
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            'Set-Cookie'?: string;
            [name: string]: unknown;
          };
          content: {
            'application/json': Record<string, never>;
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/elevation': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Lookup elevations for a list of coordinates */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['ElevationPostReq'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ElevationPostOK'];
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/geophotos': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get metadata by ID */
    get: {
      parameters: {
        query?: {
          id?: number[];
          maxLat?: number;
          maxLng?: number;
          minLat?: number;
          minLng?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              photos: components['schemas']['Geophoto'][];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/geosearch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search things that can be displayed on a map */
    get: {
      parameters: {
        query: {
          biasLat?: number;
          biasLng?: number;
          biasZoom?: number;
          debug?: boolean;
          /** @description If true the search may take longer but may be of higher quality */
          higherQuality?: boolean;
          text: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              results: components['schemas']['SearchResult'][];
              /** @description The user the search results were generated for, if any */
              user?: string;
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/munro-access/munros': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List munros */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              munros: {
                features: {
                  geometry: {
                    /** @example [
                     *       -3.992057,
                     *       56.453851
                     *     ] */
                    coordinates: [number, number];
                    /** @enum {string} */
                    type: 'Point';
                  };
                  /** @example 1 */
                  id: number;
                  properties: {
                    /** @example 930.4 */
                    meters: number;
                    /** @example Ben Chonzie */
                    name: string;
                    photo?: {
                      /** @example Angus */
                      author?: string;
                      /** @example 600 */
                      height: number;
                      /** @example https://... */
                      source: string;
                      /** @example https://www.geograph.org.uk */
                      sourceLink?: string;
                      /** @example geograph.org.uk */
                      sourceText?: string;
                      /** @example 800 */
                      width: number;
                    };
                  };
                  /** @enum {string} */
                  type: 'Feature';
                }[];
                /** @enum {string} */
                type: 'FeatureCollection';
              };
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/munro-access/pregenerated-reports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get pregenerated reports for common locations */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              reports: components['schemas']['MunroAccessReportMeta'][];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/munro-access/report/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a report */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect */
        307: {
          headers: {
            Location?: string;
            [name: string]: unknown;
          };
          content?: never;
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/munro-access/report/{id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get report generation status
     * @description To subscribe to status updates use `new EventSource('/munro-access/report/{id}/status-updates')`
     *
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MunroAccessReportStatus'];
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/munro-access/request': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a report be generated */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: date-time */
            date: string;
            /** @example Edinburgh Waverley Railway Station (EDB) */
            fromLabel: string;
            fromPoint: components['schemas']['Point'];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: components['schemas']['MunroAccessReportStatus'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get settings */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              settings: components['schemas']['Settings'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    /** Update settings */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            settings: components['schemas']['Settings'];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              settings: components['schemas']['Settings'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tracks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List tracks */
    get: {
      parameters: {
        query?: {
          orderBy?:
            | 'name'
            | 'dateAsc'
            | 'dateDesc'
            | 'dateUploadedAsc'
            | 'dateUploadedDesc';
          page?: number;
          perPage?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              page: number;
              pages: number;
              perPage: number;
              total: number;
              tracks: components['schemas']['TrackSummary'][];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    /** Create track */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            tracks?: components['schemas']['TrackCreate'][];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              tracks?: components['schemas']['Track'][];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tracks/tile/{z}/{x}/{y}.mvt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get MVT tile */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          x: components['parameters']['SlippyX'];
          y: components['parameters']['SlippyY'];
          z: components['parameters']['SlippyZ'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['MVTTile'];
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/tracks/track/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get track */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              track: components['schemas']['Track'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    /** Delete track */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': Record<string, never>;
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    options?: never;
    head?: never;
    /** Update track */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            track: components['schemas']['TrackUpdate'];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              track: components['schemas']['Track'];
            };
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    trace?: never;
  };
  '/weather/short-uk': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Find short format weather forecasts for a place in the UK */
    get: {
      parameters: {
        query: {
          /**
           * @description A place to search for
           * @example ben nevis
           */
          query: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': string;
          };
        };
        default: components['responses']['DefaultErrorResponse'];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthenticateBrowserOK: {
      user: components['schemas']['User'];
    };
    AuthenticateOK: {
      token: components['schemas']['Token'];
      user: components['schemas']['User'];
    };
    AuthenticateReq: {
      /** @example user@example.com */
      email: string;
      /** @example password */
      password: string;
    };
    AuthRegisterRequest: {
      /** @example john.doe@example.com */
      email: string;
      /** @example John Doe */
      name: string;
      /** @example password */
      password: string;
    };
    AuthRevokeReq: {
      token: components['schemas']['Token'];
    };
    /** @example {
     *       "code": 500,
     *       "message": "internal server error (correlation id cor_e0a3b2628acbb22dad4696acaf30be88)"
     *     } */
    DefaultError: {
      code: number;
      message: string;
      retryAfterSeconds?: number;
      validationErrors?: components['schemas']['ValidationErrors'];
    };
    /** @example {
     *       "elevation": [
     *         2518,
     *         2518,
     *         2518
     *       ]
     *     } */
    ElevationPostOK: {
      elevation: number[];
    };
    /** @example {
     *       "coordinates": [
     *         [
     *           -105.883643,
     *           40.176097
     *         ],
     *         [
     *           -105.861114,
     *           40.150743
     *         ],
     *         [
     *           -105.822319,
     *           40.14182
     *         ]
     *       ]
     *     } */
    ElevationPostReq: {
      coordinates: [number, number][];
    };
    /** @example {
     *       "type": "Point",
     *       "coordinates": [
     *         51,
     *         0
     *       ]
     *     } */
    Geometry: geojson.Geometry;
    Geophoto: {
      attributionLink?: string;
      attributionText?: string;
      /** Format: date-time */
      dateTaken?: string;
      id: number;
      image: components['schemas']['Image'];
      /** Format: date-time */
      indexedAt?: string;
      licenses?: number[];
      point: components['schemas']['Point'];
      smallImage?: components['schemas']['Image'];
      source?: number;
      /** @description The source's id for this image */
      sourceID?: string;
      title?: string;
    };
    Image: {
      height: number;
      src: string;
      width: number;
    };
    MunroAccessReportMeta: {
      /** Format: date-time */
      date: string;
      /** @example Edinburgh Waverley Railway Station (EDB) */
      fromLabel: string;
      fromPoint: components['schemas']['Point'];
      /** @example mar_2gnkznnp7j5ef54jfqgxnxszsc */
      id: string;
      /** Format: date-time */
      requestTime: string;
      slug: string;
      /**
       * @description URL to report JSON
       * @example https://...
       */
      url?: string;
    };
    MunroAccessReportStatus: {
      /** @example 1724364326040-0 */
      id: string;
      report: components['schemas']['MunroAccessReportMeta'];
      /** @enum {string} */
      status: 'received' | 'working' | 'ready';
      /** Format: date-time */
      timestamp: string;
    };
    /**
     * @description longitude, latitude
     * @example [
     *       -3.36459,
     *       55.94839
     *     ]
     */
    Point: [number, number];
    /**
     * @description Google Maps encoded Polyline (see https://developers.google.com/maps/documentation/utilities/polylineutility)
     * @example _p~iF~ps|U_ulLnnqC_mqNvxq`@
     */
    Polyline: string;
    SearchResult: {
      countryCode2: string;
      debug?: {
        [key: string]: unknown;
      };
      geometry: components['schemas']['Geometry'];
      id: string;
      name: string;
      /** @enum {string} */
      type:
        | 'postcode'
        | 'hill'
        | 'street'
        | 'populated_place'
        | 'water_body'
        | 'other';
    };
    /** @example session=plantoposecret_db480e5c2aa6f443ff721116b352e88c396351fd20eee0c95ed272cba311edd6890f6759931d2cdca4acb16d90a8d2af0ee9af83b35446fda1c8e272fa378462; ... */
    SetSessionCookieHeader: string;
    Settings: {
      /** @enum {string} */
      units?: 'metric' | 'customary';
    };
    /** @example plantoposecret_db480e5c2aa6f443ff721116b352e88c396351fd20eee0c95ed272cba311edd6890f6759931d2cdca4acb16d90a8d2af0ee9af83b35446fda1c8e272fa378462 */
    Token: string;
    Track: {
      /** Format: date-time */
      date: string;
      /** Format: date-time */
      dateUploaded: string;
      descriptionMd?: string;
      durationSecs?: number;
      id: string;
      lengthMeters: number;
      line: components['schemas']['Polyline'];
      name?: string;
      ownerID: string;
      times?: string[];
    };
    TrackCreate: {
      /** Format: date-time */
      date: string;
      descriptionMd?: string;
      line: components['schemas']['Polyline'];
      name?: string;
      times?: string[];
    };
    TrackSummary: {
      /** Format: date-time */
      date: string;
      /** Format: date-time */
      dateUploaded: string;
      descriptionMd?: string;
      durationSecs?: number;
      id: string;
      lengthMeters: number;
      name?: string;
      ownerID: string;
      simplifiedLine: components['schemas']['Polyline'];
    };
    TrackUpdate: {
      /** Format: date-time */
      date?: string;
      descriptionMd?: string;
      line?: components['schemas']['Polyline'];
      name?: string;
      times?: string[];
    };
    User: {
      /** @example john.doe@example.com */
      email: string;
      /** @example true */
      emailConfirmed?: boolean;
      id: components['schemas']['UserID'];
      /** @example John Doe */
      name?: string;
    };
    /** @example u_248h248h248h248h248h248h24 */
    UserID: string;
    ValidationErrors: {
      fieldErrors?: {
        [key: string]: string;
      };
      generalErrors?: string[];
    };
  };
  responses: {
    /** @description Error */
    DefaultErrorResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['DefaultError'];
      };
    };
    /** @description OK */
    MVTTile: {
      headers: {
        'Content-Encoding'?: string;
        [name: string]: unknown;
      };
      content: {
        'application/vnd.mapbox-vector-tile': string;
      };
    };
  };
  parameters: {
    SlippyX: number;
    SlippyY: number;
    SlippyZ: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
