apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  labels:
    app: api-server
  namespace: pt
spec:
  secretName: api-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "api.plantopo.com"
