apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: pt
  labels:
    app: api-server
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      name: api-server
      labels:
        app: api-server
        ver: {{ .Values.ver }}
    spec:
      containers:
        - name: api-server
          image: {{ .Values.image}}
          env:
            - name: PORT
              value: "8080"
            - name: PT_MAILGUN_KEY
              valueFrom:
                secretKeyRef:
                  key: PT_MAILGUN_KEY
                  name: api-server
            - name: PT_EMAILABLE_KEY
              valueFrom:
                  secretKeyRef:
                    key: PT_EMAILABLE_KEY
                    name: api-server
            - name: SESSION_AUTHENTICATION_KEY
              valueFrom:
                secretKeyRef:
                  key: SESSION_AUTHENTICATION_KEY
                  name: api-server
            - name: PT_FRONTEND_MAP_TOKENS
              valueFrom:
                  secretKeyRef:
                    key: PT_FRONTEND_MAP_TOKENS
                    name: api-server
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: db
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: http
            periodSeconds: 5
