apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: pt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        k8s.grafana.com/scrape: "true"
        k8s.grafana.com/metrics.portName: "meta"
        k8s.grafana.com/job: "api"
    spec:
      containers:
        - name: api
          image: ghcr.io/dzfranklin/plantopo-api:latest
          ports:
            - name: http
              containerPort: 4000
            - name: admin
              containerPort: 4002
            - name: meta
              containerPort: 4001
          env:
            - name: APP_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: META_PORT
              value: "4001"
            - name: ADMIN_PORT
              value: "4002"
            - name: DOMAIN
              value: plantopo.com
            - name: CORS_ALLOW_HOSTS
              value: "plantopo.com,admin.plantopo.com,localhost,pt.internal,admin.pt.internal"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
            - name: REDIS_ADDR
              value: "redis.pt.svc.cluster.local:6379"
            - name: S3_ENDPOINT
              value: "minio.dfranklin.dev"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: secret_key
            - name: OS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ordnancesurvey
                  key: api_key
            - name: MET_OFFICE_DATAPOINT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: metoffice
                  key: datapoint_api_key
            - name: DFT_BUS_OPEN_DATA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dft-bus-opendata
                  key: username
            - name: DFT_BUS_OPEN_DATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dft-bus-opendata
                  key: password
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio
                  key: account_sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio
                  key: auth_token
            - name: IMGPROXY_KEY
              valueFrom:
                secretKeyRef:
                  name: imgproxy
                  key: key
            - name: IMGPROXY_SALT
              valueFrom:
                secretKeyRef:
                  name: imgproxy
                  key: salt
            - name: SMTP_RELAY_SERVER
              valueFrom:
                secretKeyRef:
                  name: sendgrid-smtp
                  key: server
            - name: SMTP_RELAY_PORT
              valueFrom:
                secretKeyRef:
                  name: sendgrid-smtp
                  key: port
            - name: SMTP_RELAY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sendgrid-smtp
                  key: username
            - name: SMTP_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sendgrid-smtp
                  key: password
            - name: FLICKR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: flickr
                  key: api-key
            - name: GEOGRAPH_IMAGE_SECRET
              valueFrom:
                secretKeyRef:
                  name: geograph
                  key: image_secret
            - name: ELEVATION_DEM_DATASET
              valueFrom:
                secretKeyRef:
                  name: elevation
                  key: dem_dataset
          livenessProbe:
            httpGet:
              path: /status
              port: http
