apiVersion: v1
kind: Service
metadata:
  name: matchmaker
  labels:
    app: matchmaker
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
      app: matchmaker
  ports:
    - name: grpc
      port: 5050
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matchmaker
  labels:
      app: matchmaker
spec:
  serviceName: matchmaker
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
        ver: "{{ .Values.ver }}"
    spec:
      containers:
        - name: matchmaker
          image: "{{ .Values.image }}"
          env:
            - name: PORT
              value: "5050"
            - name: APP_ENV
              value: "{{ .Values.env }}"
          ports:
            - containerPort: 5050
              name: grpc
          livenessProbe:
            tcpSocket:
              port: 5050
            periodSeconds: 5
