apiVersion: v1
kind: Service
metadata:
  name: sync-backend
  labels:
      app: sync-backend
spec:
  type: ClusterIP
  selector:
    app: sync-backend
  ports:
    - name: grpc
      port: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-backend
  labels:
    app: sync-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sync-backend
  template:
    metadata:
      labels:
        app: sync-backend
        ver: "{{ .Values.ver }}"
    spec:
      containers:
        - name: sync-backend
          image: "{{ .Values.image }}"
          env:
            - name: PORT
              value: "5050"
            - name: APP_ENV
              value: "{{ .Values.env }}"
            - name: __POD_IP # For SELF_EXTERNAL_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SELF_EXTERNAL_ADDR
              value: "$(__POD_IP):5050"
            - name: EXPORT_BUCKET
              value: "{{ .Values.exportBucket }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db
                  key: DATABASE_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: sync-backend-aws-credentials
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sync-backend-aws-credentials
                  key: secret_access_key
          ports:
            - containerPort: 5050
              name: grpc
          livenessProbe:
            tcpSocket:
              port: grpc
            periodSeconds: 5
