// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package psqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	UserID pgtype.UUID
}

type AuditLog struct {
	ID      int64
	Time    pgtype.Timestamp
	Subject string
	Object  string
	Action  string
	Payload []byte
}

type AuthorizedSmsSender struct {
	ID         pgtype.UUID
	InsertedAt pgtype.Timestamp
	NumberE164 string
	Comment    pgtype.Text
}

type BritishAndIrishHill struct {
	ID             int32
	Name           pgtype.Text
	Point          interface{}
	SmcParentID    pgtype.Int4
	Classification []string
	Map50k         pgtype.Text
	Map25k         pgtype.Text
	Metres         pgtype.Float8
	GridRef        pgtype.Text
	GridRef10      pgtype.Text
	Drop           pgtype.Float8
	ColGridRef     pgtype.Text
	ColHeight      pgtype.Float8
	Feature        pgtype.Text
	Observations   pgtype.Text
	Survey         pgtype.Text
	Country        pgtype.Text
	Revision       pgtype.Text
	Comments       pgtype.Text
}

type BritishAndIrishHillPhoto struct {
	ID         int64
	HillID     int32
	Caption    pgtype.Text
	Licenses   []string
	Source     string
	Size       int32
	Width      int32
	Height     int32
	UploadedAt pgtype.Timestamp
	Author     pgtype.Text
	SourceText pgtype.Text
	SourceLink pgtype.Text
	Importer   pgtype.Text
	Rank       int32
	Reviewed   bool
}

type FlickrIndexProgress struct {
	RegionID int32
	Latest   pgtype.Timestamptz
}

type FlickrIndexRegion struct {
	ID     int32
	Name   string
	MinLng float64
	MinLat float64
	MaxLng float64
	MaxLat float64
}

type GeographIndexProgress struct {
	ID     int32
	Cutoff pgtype.Int4
}

type Geophoto struct {
	ID              int64
	Source          pgtype.Int4
	SourceID        pgtype.Text
	IndexRegionID   pgtype.Int4
	IndexedAt       pgtype.Timestamptz
	AttributionText pgtype.Text
	AttributionLink pgtype.Text
	Licenses        []int32
	Url             string
	Width           int32
	Height          int32
	SmallUrl        pgtype.Text
	SmallWidth      pgtype.Int4
	SmallHeight     pgtype.Int4
	Point           interface{}
	Title           pgtype.Text
	DateTaken       pgtype.Timestamptz
}

type GeophotosLicense struct {
	ID   int32
	Name string
	Url  pgtype.Text
}

type GeophotosSource struct {
	ID   int32
	Name pgtype.Text
}

type PendingEmailConfirmationToken struct {
	Email     pgtype.Text
	Token     string
	CreatedAt pgtype.Timestamp
}

type PendingPasswordResetToken struct {
	Email     pgtype.Text
	Token     string
	CreatedAt pgtype.Timestamp
}

type Session struct {
	Token       string
	UserID      pgtype.UUID
	CreatedAt   pgtype.Timestamp
	ExpiryStart pgtype.Timestamp
	UserAgent   pgtype.Text
	IpAddr      *netip.Addr
}

type User struct {
	ID             pgtype.UUID
	Name           pgtype.Text
	Email          string
	EmailConfirmed pgtype.Bool
	PasswordHash   []byte
	CreatedAt      pgtype.Timestamp
}
