CREATE SCHEMA pt;

GRANT USAGE ON SCHEMA pt TO pt;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pt TO pt;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA pt TO pt;

ALTER DEFAULT PRIVILEGES IN SCHEMA pt GRANT ALL PRIVILEGES ON TABLES TO pt;

ALTER DEFAULT PRIVILEGES IN SCHEMA pt GRANT ALL PRIVILEGES ON SEQUENCES TO pt;

GRANT ALL PRIVILEGES ON public.schema_migrations TO pt;
