CREATE SCHEMA IF NOT EXISTS pt;

GRANT USAGE ON SCHEMA pt TO {{user}};

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pt TO {{user}};

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA pt TO {{user}};

ALTER DEFAULT PRIVILEGES IN SCHEMA pt GRANT ALL PRIVILEGES ON TABLES TO {{user}};

ALTER DEFAULT PRIVILEGES IN SCHEMA pt GRANT ALL PRIVILEGES ON SEQUENCES TO {{user}};

GRANT ALL PRIVILEGES ON public.schema_migrations TO {{user}};
