[package]
name = "pt-layer-data-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre.workspace = true
eyre.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
