package metoffice

var significantWeatherDescriptions = map[string]string{
	"NA": "Not available",
	"0":  "Clear night",
	"1":  "Sunny day",
	"2":  "Partly cloudy (night)",
	"3":  "Partly cloudy (day)",
	"4":  "Not used",
	"5":  "Mist",
	"6":  "Fog",
	"7":  "Cloudy",
	"8":  "Overcast",
	"9":  "Light rain shower (night)",
	"10": "Light rain shower (day)",
	"11": "Drizzle",
	"12": "Light rain",
	"13": "Heavy rain shower (night)",
	"14": "Heavy rain shower (day)",
	"15": "Heavy rain",
	"16": "Sleet shower (night)",
	"17": "Sleet shower (day)",
	"18": "Sleet",
	"19": "Hail shower (night)",
	"20": "Hail shower (day)",
	"21": "Hail",
	"22": "Light snow shower (night)",
	"23": "Light snow shower (day)",
	"24": "Light snow",
	"25": "Heavy snow shower (night)",
	"26": "Heavy snow shower (day)",
	"27": "Heavy snow",
	"28": "Thunder shower (night)",
	"29": "Thunder shower (day)",
	"30": "Thunder",
}

var significantWeatherShortDescriptions = map[string]string{
	"NA": "NA",
	"0":  "Clear",
	"1":  "Sunny",
	"2":  "Partly cloudy",
	"3":  "Partly cloudy",
	"4":  "Not used",
	"5":  "Mist",
	"6":  "Fog",
	"7":  "Cloudy",
	"8":  "Overcast",
	"9":  "Light shower",
	"10": "Light shower",
	"11": "Drizzle",
	"12": "Light rain",
	"13": "Heavy shower",
	"14": "Heavy shower",
	"15": "Heavy rain",
	"16": "Sleet shower",
	"17": "Sleet shower",
	"18": "Sleet",
	"19": "Hail shower",
	"20": "Hail shower",
	"21": "Hail",
	"22": "Light snow shower",
	"23": "Light snow shower",
	"24": "Light snow",
	"25": "Heavy snow shower",
	"26": "Heavy snow shower",
	"27": "Heavy snow",
	"28": "Thunder shower",
	"29": "Thunder shower",
	"30": "Thunder",
}

var visibilityCodes = map[string]string{
	"UN": "Unknown",
	"VP": "Very poor - Less than 1 km",
	"PO": "Poor - Between 1-4 km",
	"MO": "Moderate - Between 4-10 km",
	"GO": "Good - Between 10-20 km",
	"VG": "Very good - Between 20-40 km",
	"EX": "Excellent - More than 40 km",
}
