name: check_backend
on:
  push:
    paths-ignore:
      - 'app/**'
      - 'staticmap/**'
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: docker/setup-buildx-action@v3
      - name: Install system-level dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install proj-data libproj-dev proj-bin gdal-bin libgdal-dev libvips-dev
      - uses: actions/setup-node@v4
        with:
          node-version: 'v21.7.x'
      - uses: actions/checkout@v4
      - name: Test
        run: make test
