name: Check
on: push
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: docker/setup-buildx-action@v3
      - name: Install proj
        run: |
          sudo apt-get update
          sudo apt-get -y install proj-data libproj-dev proj-bin
      - uses: actions/checkout@v4
      - name: Check
        run: ./scripts/check-in-ci.sh
