name: Deploy backends (except matchmaker)

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'app/**'

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up kubectl
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p "$HOME/.kube"
        echo $KUBECONFIG | base64 --decode > "$HOME/.kube/config"

#    - name: Setup Docker buildx
#      uses: docker/setup-buildx-action@v2

    - name: Login to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build deploy tool
      run: go build -v -o ./out/deploy ./deploy

    - name: Run deploy
      run: ./out/deploy --all --exclude-system app --exclude-system matchmaker
