name: Deploy PR to staging

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up kubectl
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          mkdir -p "$HOME/.kube"
          echo $KUBECONFIG | base64 --decode > "$HOME/.kube/config"

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build deploy tool
        run: go build -v -o ./out/deploy ./deploy

      - name: Run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
        run: ./out/deploy --all --staging "pr${{ github.event.pull_request.number }}"

      - name: Create comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployed ${{ github.ref_name }} at ${{ github.sha }} to staging at https://pr${{ github.event.pull_request.number }}.app.pt-staging.dfusercontent.com'
            })
